### ISSUE TITLE
Add Indonesian translation for `concepts/workloads/controllers/replicaset.md`

### ISSUE THREAD

**Issue by girikuncoro** [jk8s/sig-docs-id#15]
Add Indonesian translation for `concepts/workloads/controllers/replicaset.md` page

How to address this issue:
- Leave comment here that you are going to work on this and assign yourself
- Navigate to https://github.com/kubernetes/website/issues/15341 , this is main issue tracker of  our docs localization effort for current milestone
- Leave comment in the [issue tracker](https://github.com/kubernetes/website/issues/15341) that you are claiming the page
- Fork and raise PR to https://github.com/kubernetes/website
- In the PR body, add prow bot command `/language id` and `/cc @kubernetes/sig-docs-id-reviews`
- Wait to get reviews, address them, and voila you'll get PR merged!

**Comment by joshuabezaleel** [comment]
May I take this one? @girikuncoro

**Comment by irvifa** [comment]
Sure thing, you can take things that not assigned yet

**Comment by girikuncoro** [comment]
hacktoberfest is done, closing this issue
