### ISSUE TITLE
[Update] Change occurences of "kluster" into "klaster" in ID localizations

### ISSUE THREAD

**Issue by phanama** [jk8s/sig-docs-id#20]
We agreed to use `kluster` as the translation for `cluster` in our translation.
Then I found out that `klaster` is a registered word in KBBI:
https://kbbi.kemdikbud.go.id/entri/klaster

We can use it instead of `kluster`. Let's change all occurences of `kluster` to `klaster` in our docs.

@girikuncoro @irvifa

**Comment by phanama** [comment]
More information on the semantic meanings of the English word, as `klaster` might be the direct "serapan" of `cluster`

https://en.wiktionary.org/wiki/cluster

**Comment by girikuncoro** [comment]
This is good find, I think in the future we might and we will replace more words as we discover and learn new wordings. This should be supported by some scripts or automation to replace all words in Indonesian docs (reusable when we need to replace another word)

We'll pick this as action item in our next meeting

**Comment by phanama** [comment]
Maybe @wahyuoi is interested. Join our meeting this week! @wahyuoi

**Comment by irvifa** [comment]
@phanama kindly review my PR 🙇

**Comment by phanama** [comment]
Thanks for all the great work guys! 🎉 
I'm closing this issue!
