### ISSUE TITLE
Fix deadlinks in kubernetes.io/id

### ISSUE THREAD

**Issue by girikuncoro** [jk8s/sig-docs-id#22]
Some PRs addressed couple of broken links in our Indonesian page: 
https://github.com/kubernetes/website/pull/17685

Reference: https://github.com/butuzov/deadlinks

According to Oleg, he has some tools to fix this:
```
docker run --rm -it -v "$(pwd):/src" docker.io/butuzov/deadlinks:0.1.1 https://kubernetes.io/id/ 
```

Note from him: https://kubernetes.slack.com/archives/CJ1LUCUHM/p1574241950025200
> here https://github.com/butuzov/deadlinks and > https://deadlinks.readthedocs.io/en/latest/examples/index.html a bit more examples, but not much > =(. having bad time in writing own docs

**Comment by butuzov** [comment]
@girikuncoro just in case, I am having bad time to work at anything, not just docs, so I am doing what I can in my situation. If you have any problems or issues just let  me know hear or via slack or via linkedin.

**Comment by girikuncoro** [comment]
will do, thanks a lot @butuzov !

**Comment by girikuncoro** [comment]
@irvifa has put deadline links checker in CI: https://circleci.com/gh/jk8s/sig-docs-id/35

**Comment by butuzov** [comment]
Hi @girikuncoro, i guess you can close this issue =). I am happy my tool helped a bit.

**Comment by girikuncoro** [comment]
Yes @butuzov thanks a lot for your help :) we have included your script in the CI that will help us fix
